
DECLARE
  l_table_count NUMBER(1);
BEGIN

  SELECT COUNT(*)
    INTO l_table_count
    FROM user_tables
   WHERE table_name = 'JAVA_DATE_TIME_ORACLE_ECLIPSELINK';

  IF l_table_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE JAVA_DATE_TIME_ORACLE_ECLIPSELINK';
  END IF;
END;!!

CREATE TABLE JAVA_DATE_TIME_ORACLE_ECLIPSELINK (
  ID NUMBER NOT NULL,
  OFFSET_COLUMN TIMESTAMP(6) WITH TIME ZONE,
  ZONE_COLUMN TIMESTAMP(6) WITH TIME ZONE,
  CALENDAR_COLUMN TIMESTAMP(6) WITH TIME ZONE,
  YEAR_TO_MONTH_COLUMN INTERVAL YEAR(9) TO MONTH,
  DAY_TO_SECOND_COLUMN INTERVAL DAY(9) TO SECOND(9),
  PRIMARY KEY (ID)
)!!