
DECLARE
  l_table_count NUMBER(1);
BEGIN

  SELECT COUNT(*)
    INTO l_table_count
    FROM user_tables
   WHERE table_name = 'JAVA_TIME_WITH_ZONE';

  IF l_table_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE JAVA_TIME_WITH_ZONE';
  END IF;
END;!!

CREATE TABLE JAVA_TIME_WITH_ZONE (
  ID NUMBER(8) NOT NULL,
  ZONED_TIME TIMESTAMP(9) WITH TIME ZONE,
  OFFSET_TIME TIMESTAMP(9) WITH TIME ZONE,
  YEAR_TO_MONTH_COLUMN INTERVAL YEAR(9) TO MONTH,
  DAY_TO_SECOND_COLUMN INTERVAL DAY(9) TO SECOND(9),
  PRIMARY KEY (ID)
)!!
