CREATE TABLE JAVA_TIME_42 (
  ID BIGINT NOT NULL,
  TIME_COLUMN TIME,
  PRIMARY KEY (ID)
);

CREATE TABLE JAVA_TIMESTAMP_42 (
  ID BIGINT NOT NULL,
  TIMESTAMP_COLUMN TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE JAVA_DATE_42 (
  ID BIGINT NOT NULL,
  DATE_COLUMN DATE,
  PRIMARY KEY (ID)
);

