EXECUTE BLOCK AS BEGIN
  IF (EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'JAVA_TIME_42')) THEN
    EXECUTE STATEMENT 'DROP TABLE JAVA_TIME_42;';
END!!

EXECUTE BLOCK AS BEGIN
  IF (EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'JAVA_TIMESTAMP_42')) THEN
    EXECUTE STATEMENT 'DROP TABLE JAVA_TIMESTAMP_42;';
END!!

EXECUTE BLOCK AS BEGIN
  IF (EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'JAVA_DATE_42')) THEN
    EXECUTE STATEMENT 'DROP TABLE JAVA_DATE_42;';
END!!

CREATE TABLE JAVA_TIME_42 (
  ID BIGINT NOT NULL,
  TIME_COLUMN TIME,
  PRIMARY KEY (ID)
)!!

CREATE TABLE JAVA_TIMESTAMP_42 (
  ID BIGINT NOT NULL,
  TIMESTAMP_COLUMN TIMESTAMP,
  PRIMARY KEY (ID)
)!!

CREATE TABLE JAVA_DATE_42 (
  ID BIGINT NOT NULL,
  DATE_COLUMN DATE,
  PRIMARY KEY (ID)
)!!
