CREATE TABLE JAVA_TIME_42 (
  ID INT NOT NULL,
  DATE_COLUMN DATE,
  TIME_COLUMN TIME(9),
  TIMESTAMP_COLUMN TIMESTAMP(9),
  PRIMARY KEY (ID)
);

CREATE TABLE JAVA_TIME_42_WITH_ZONE (
  ID INT NOT NULL,
  OFFSET_DATE_TIME_COLUMN TIMESTAMP(9) WITH TIME ZONE,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_TIME_42_ZONED;
CREATE TABLE JAVA_TIME_42_ZONED (
  ID BIGINT NOT NULL,
  TIMESTAMP_UTC TIMESTAMP(9) WITH TIME ZONE,
  ZONE_ID VARCHAR(32),
  PRIMARY KEY (ID)
);
