DROP TABLE IF EXISTS JAVA_TIME_42;
CREATE TABLE JAVA_TIME_42 (
  ID BIGINT NOT NULL,
  TIME_COLUMN TIME(6),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_TIMESTAMP_42;
CREATE TABLE JAVA_TIMESTAMP_42 (
  ID BIGINT NOT NULL,
  TIMESTAMP_COLUMN DATETIME(6),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_DATE_42;
CREATE TABLE JAVA_DATE_42 (
  ID BIGINT NOT NULL,
  DATE_COLUMN DATE,
  PRIMARY KEY (ID)
);
