DROP TABLE IF EXISTS JAVA_TIME_42;
CREATE TABLE JAVA_TIME_42 (
  ID BIGINT NOT NULL,
  DATE_COLUMN DATE,
  TIME_COLUMN TIME,
-- travis has a version that is older than the sin
--  TIMESTAMP_COLUMN TIMESTAMP(6),
  TIMESTAMP_COLUMN TIMESTAMP,
  PRIMARY KEY (ID)
);
