DROP TABLE IF EXISTS JAVA_TIME_42;
CREATE TABLE JAVA_TIME_42 (
  ID BIGINT NOT NULL,
  DATE_COLUMN DATE,
  TIME_COLUMN TIME(9),
  TIMESTAMP_COLUMN TIMESTAMP(9),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_TIME_42_WITH_ZONE;
CREATE TABLE JAVA_TIME_42_WITH_ZONE (
  ID BIGINT NOT NULL,
  OFFSET_DATE_TIME_COLUMN TIMESTAMP(9) WITH TIME ZONE,
  PRIMARY KEY (ID)
);
