
DECLARE
  l_table_count NUMBER(1);
BEGIN

  SELECT COUNT(*)
    INTO l_table_count
    FROM user_tables
   WHERE table_name = 'JAVA_TIMESTAMP_42';

  IF l_table_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE JAVA_TIMESTAMP_42';
  END IF;
END;!!

DECLARE
  l_table_count NUMBER(1);
BEGIN

  SELECT COUNT(*)
    INTO l_table_count
    FROM user_tables
   WHERE table_name = 'JAVA_DATE_42';

  IF l_table_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE JAVA_DATE_42';
  END IF;
END;!!

DECLARE
  l_table_count NUMBER(1);
BEGIN

  SELECT COUNT(*)
    INTO l_table_count
    FROM user_tables
   WHERE table_name = 'JAVA_TIME_42_WITH_ZONE';

  IF l_table_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE JAVA_TIME_42_WITH_ZONE';
  END IF;
END;!!

CREATE TABLE JAVA_TIMESTAMP_42 (
  ID NUMBER(18) NOT NULL,
  TIMESTAMP_COLUMN TIMESTAMP(9),
  PRIMARY KEY (ID)
)!!

CREATE TABLE JAVA_DATE_42 (
  ID NUMBER(18) NOT NULL,
  DATE_COLUMN DATE,
  PRIMARY KEY (ID)
)!!

CREATE TABLE JAVA_TIME_42_WITH_ZONE (
  ID NUMBER(18) NOT NULL,
  OFFSET_DATE_TIME_COLUMN TIMESTAMP(9) WITH TIME ZONE,
  PRIMARY KEY (ID)
)!!
