DROP TABLE IF EXISTS JAVA_TIME_42;
CREATE TABLE JAVA_TIME_42 (
  ID BIGINT NOT NULL,
  TIME_COLUMN TIME(6),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_TIMESTAMP_42;
CREATE TABLE JAVA_TIMESTAMP_42 (
  ID BIGINT NOT NULL,
  TIMESTAMP_COLUMN TIMESTAMP(6),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_DATE_42;
CREATE TABLE JAVA_DATE_42 (
  ID BIGINT NOT NULL,
  DATE_COLUMN DATE,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_TIME_42_WITH_ZONE;
CREATE TABLE JAVA_TIME_42_WITH_ZONE (
  ID BIGINT NOT NULL,
  OFFSET_DATE_TIME_COLUMN TIMESTAMP(6) WITH TIME ZONE,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_TIMESTAMP_42_ZONED;
CREATE TABLE JAVA_TIMESTAMP_42_ZONED (
  ID BIGINT NOT NULL,
  TIMESTAMP_UTC TIMESTAMP(6) WITH TIME ZONE,
  ZONE_ID VARCHAR(32),
  PRIMARY KEY (ID)
);
