DROP TABLE IF EXISTS JAVA_TIME_42;
CREATE TABLE JAVA_TIME_42 (
  ID BIGINT NOT NULL,
  TIME_COLUMN TIME(7),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_TIMESTAMP_42;
CREATE TABLE JAVA_TIMESTAMP_42 (
  ID BIGINT NOT NULL,
  TIMESTAMP_COLUMN datetime2(7),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_DATE_42;
CREATE TABLE JAVA_DATE_42 (
  ID BIGINT NOT NULL,
  DATE_COLUMN DATE,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_TIME_42_WITH_ZONE;
CREATE TABLE JAVA_TIME_42_WITH_ZONE (
  ID BIGINT NOT NULL,
  OFFSET_DATE_TIME_COLUMN datetimeoffset(7),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JAVA_TIMESTAMP_42_ZONED;
CREATE TABLE JAVA_TIMESTAMP_42_ZONED (
  ID BIGINT NOT NULL,
  TIMESTAMP_UTC datetimeoffset(7),
  ZONE_ID VARCHAR(32),
  PRIMARY KEY (ID)
);
