package oracle.sql;


/**
 * Dummy {@code ZONEIDMAP} interface which avoids a dependency to OJDBC.
 * 
 * <p>
 * Will be removed from final JAR.
 */
public class ZONEIDMAP {

  private static final int INV_ZONEID = -1;

  public static int getID(String paramString) {
    if (paramString == null) {
      return INV_ZONEID;
    }

    switch (paramString) {
      case "Africa/Asmera":
        return 46;
      case "Africa/Bamako":
        return 58;
      case "Africa/Bangui":
        return 37;
      case "Africa/Banjul":
        return 49;
      case "Africa/Bissau":
        return 52;
      case "Africa/Blantyre":
        return 57;
      case "Africa/Brazzaville":
        return 41;
      case "Africa/Bujumbura":
        return 35;
      case "Africa/Cairo":
        return 44;
      case "Africa/Casablanca":
        return 61;
      case "Africa/Ceuta":
        return 81;
      case "Africa/Conakry":
        return 51;
      case "Africa/Dakar":
        return 69;
      case "Africa/Dar_es_Salaam":
        return 75;
      case "Africa/Djibouti":
        return 43;
      case "Africa/Douala":
        return 36;
      case "Africa/El_Aaiun":
        return 62;
      case "Africa/Freetown":
        return 70;
      case "Africa/Gaborone":
        return 33;
      case "Africa/Harare":
        return 80;
      case "Africa/Johannesburg":
        return 72;
      case "Africa/Kampala":
        return 78;
      case "Africa/Khartoum":
        return 73;
      case "Africa/Kigali":
        return 67;
      case "Africa/Kinshasa":
        return 39;
      case "Africa/Lagos":
        return 66;
      case "Africa/Libreville":
        return 48;
      case "Africa/Lome":
        return 76;
      case "Africa/Luanda":
        return 31;
      case "Africa/Lubumbashi":
        return 40;
      case "Africa/Lusaka":
        return 79;
      case "Africa/Malabo":
        return 45;
      case "Africa/Maputo":
        return 63;
      case "Africa/Maseru":
        return 54;
      case "Africa/Mbabane":
        return 74;
      case "Africa/Mogadishu":
        return 71;
      case "Africa/Monrovia":
        return 55;
      case "Africa/Nairobi":
        return 53;
      case "Africa/Ndjamena":
        return 38;
      case "Africa/Niamey":
        return 65;
      case "Africa/Nouakchott":
        return 60;
      case "Africa/Ouagadougou":
        return 34;
      case "Africa/Porto-Novo":
        return 32;
      case "Africa/Sao_Tome":
        return 68;
      case "Africa/Timbuktu":
        return 59;
      case "Africa/Tripoli":
        return 56;
      case "Africa/Tunis":
        return 77;
      case "Africa/Windhoek":
        return 64;
      case "America/Adak":
        return 108;
      case "America/Anchorage":
        return 106;
      case "America/Anguilla":
        return 146;
      case "America/Antigua":
        return 147;
      case "America/Araguaina":
        return 186;
      case "America/Aruba":
        return 181;
      case "America/Asuncion":
        return 200;
      case "America/Atka":
        return 620;
      case "America/Barbados":
        return 149;
      case "America/Belem":
        return 184;
      case "America/Belize":
        return 150;
      case "America/Boa_Vista":
        return 191;
      case "America/Bogota":
        return 195;
      case "America/Boise":
        return 110;
      case "America/Buenos_Aires":
        return 175;
      case "America/Cambridge_Bay":
        return 135;
      case "America/Cancun":
        return 140;
      case "America/Caracas":
        return 205;
      case "America/Catamarca":
        return 179;
      case "America/Cayenne":
        return 198;
      case "America/Cayman":
        return 151;
      case "America/Chicago":
        return 101;
      case "America/Chihuahua":
        return 142;
      case "America/Cordoba":
        return 177;
      case "America/Costa_Rica":
        return 152;
      case "America/Cuiaba":
        return 189;
      case "America/Curacao":
        return 196;
      case "America/Dawson":
        return 139;
      case "America/Dawson_Creek":
        return 131;
      case "America/Denver":
        return 102;
      case "America/Detroit":
        return 116;
      case "America/Dominica":
        return 154;
      case "America/Edmonton":
        return 129;
      case "America/El_Salvador":
        return 156;
      case "America/Ensenada":
        return 657;
      case "America/Fort_Wayne":
        return 623;
      case "America/Fortaleza":
        return 185;
      case "America/Glace_Bay":
        return 121;
      case "America/Godthab":
        return 207;
      case "America/Goose_Bay":
        return 119;
      case "America/Grand_Turk":
        return 172;
      case "America/Grenada":
        return 157;
      case "America/Guadeloupe":
        return 158;
      case "America/Guatemala":
        return 159;
      case "America/Guayaquil":
        return 197;
      case "America/Guyana":
        return 199;
      case "America/Halifax":
        return 120;
      case "America/Havana":
        return 153;
      case "America/Hermosillo":
        return 143;
      case "America/Indiana/Indianapolis":
        return 1647;
      case "America/Indiana/Knox":
        return 113;
      case "America/Indiana/Marengo":
        return 112;
      case "America/Indiana/Vevay":
        return 114;
      case "America/Indianapolis":
        return 111;
      case "America/Inuvik":
        return 137;
      case "America/Iqaluit":
        return 133;
      case "America/Jamaica":
        return 162;
      case "America/Jujuy":
        return 178;
      case "America/Juneau":
        return 104;
      case "America/Knox_IN":
        return 625;
      case "America/La_Paz":
        return 182;
      case "America/Lima":
        return 201;
      case "America/Los_Angeles":
        return 103;
      case "America/Louisville":
        return 115;
      case "America/Maceio":
        return 187;
      case "America/Managua":
        return 165;
      case "America/Manaus":
        return 192;
      case "America/Martinique":
        return 163;
      case "America/Mazatlan":
        return 144;
      case "America/Mendoza":
        return 180;
      case "America/Menominee":
        return 117;
      case "America/Mexico_City":
        return 141;
      case "America/Miquelon":
        return 170;
      case "America/Montevideo":
        return 204;
      case "America/Montreal":
        return 122;
      case "America/Montserrat":
        return 164;
      case "America/Nassau":
        return 148;
      case "America/New_York":
        return 100;
      case "America/Nipigon":
        return 124;
      case "America/Nome":
        return 107;
      case "America/Noronha":
        return 183;
      case "America/Panama":
        return 166;
      case "America/Pangnirtung":
        return 132;
      case "America/Paramaribo":
        return 202;
      case "America/Phoenix":
        return 109;
      case "America/Port-au-Prince":
        return 160;
      case "America/Port_of_Spain":
        return 203;
      case "America/Porto_Acre":
        return 193;
      case "America/Porto_Velho":
        return 190;
      case "America/Puerto_Rico":
        return 167;
      case "America/Rainy_River":
        return 125;
      case "America/Rankin_Inlet":
        return 134;
      case "America/Regina":
        return 127;
      case "America/Rosario":
        return 176;
      case "America/Santiago":
        return 194;
      case "America/Santo_Domingo":
        return 155;
      case "America/Sao_Paulo":
        return 188;
      case "America/Scoresbysund":
        return 206;
      case "America/Shiprock":
        return 1638;
      case "America/St_Johns":
        return 118;
      case "America/St_Kitts":
        return 168;
      case "America/St_Lucia":
        return 169;
      case "America/St_Thomas":
        return 174;
      case "America/St_Vincent":
        return 171;
      case "America/Swift_Current":
        return 128;
      case "America/Tegucigalpa":
        return 161;
      case "America/Thule":
        return 208;
      case "America/Thunder_Bay":
        return 123;
      case "America/Tijuana":
        return 145;
      case "America/Tortola":
        return 173;
      case "America/Vancouver":
        return 130;
      case "America/Virgin":
        return 686;
      case "America/Whitehorse":
        return 138;
      case "America/Winnipeg":
        return 126;
      case "America/Yakutat":
        return 105;
      case "America/Yellowknife":
        return 136;
      case "Antarctica/Casey":
        return 230;
      case "Antarctica/Davis":
        return 231;
      case "Antarctica/DumontDUrville":
        return 233;
      case "Antarctica/Mawson":
        return 232;
      case "Antarctica/McMurdo":
        return 236;
      case "Antarctica/Palmer":
        return 235;
      case "Antarctica/South_Pole":
        return 748;
      case "Antarctica/Syowa":
        return 234;
      case "Asia/Aden":
        return 302;
      case "Asia/Almaty":
        return 269;
      case "Asia/Amman":
        return 268;
      case "Asia/Anadyr":
        return 312;
      case "Asia/Aqtau":
        return 271;
      case "Asia/Aqtobe":
        return 270;
      case "Asia/Ashkhabad":
        return 297;
      case "Asia/Baghdad":
        return 265;
      case "Asia/Bahrain":
        return 243;
      case "Asia/Baku":
        return 242;
      case "Asia/Bangkok":
        return 296;
      case "Asia/Beirut":
        return 277;
      case "Asia/Bishkek":
        return 272;
      case "Asia/Brunei":
        return 246;
      case "Asia/Calcutta":
        return 260;
      case "Asia/Chungking":
        return 251;
      case "Asia/Colombo":
        return 293;
      case "Asia/Dacca":
        return 244;
      case "Asia/Damascus":
        return 294;
      case "Asia/Dili":
        return 259;
      case "Asia/Dubai":
        return 298;
      case "Asia/Dushanbe":
        return 295;
      case "Asia/Gaza":
        return 285;
      case "Asia/Harbin":
        return 249;
      case "Asia/Hong_Kong":
        return 254;
      case "Asia/Hovd":
        return 280;
      case "Asia/Irkutsk":
        return 307;
      case "Asia/Istanbul":
        return 1431;
      case "Asia/Jakarta":
        return 261;
      case "Asia/Jayapura":
        return 263;
      case "Asia/Jerusalem":
        return 266;
      case "Asia/Kabul":
        return 240;
      case "Asia/Kamchatka":
        return 311;
      case "Asia/Karachi":
        return 284;
      case "Asia/Kashgar":
        return 253;
      case "Asia/Katmandu":
        return 282;
      case "Asia/Krasnoyarsk":
        return 306;
      case "Asia/Kuala_Lumpur":
        return 278;
      case "Asia/Kuching":
        return 279;
      case "Asia/Kuwait":
        return 275;
      case "Asia/Macao":
        return 256;
      case "Asia/Magadan":
        return 310;
      case "Asia/Manila":
        return 286;
      case "Asia/Muscat":
        return 283;
      case "Asia/Nicosia":
        return 257;
      case "Asia/Novosibirsk":
        return 305;
      case "Asia/Omsk":
        return 304;
      case "Asia/Phnom_Penh":
        return 248;
      case "Asia/Pyongyang":
        return 274;
      case "Asia/Qatar":
        return 287;
      case "Asia/Rangoon":
        return 247;
      case "Asia/Riyadh":
        return 288;
      case "Asia/Riyadh87":
        return 289;
      case "Asia/Riyadh88":
        return 290;
      case "Asia/Riyadh89":
        return 291;
      case "Asia/Saigon":
        return 301;
      case "Asia/Samarkand":
        return 299;
      case "Asia/Seoul":
        return 273;
      case "Asia/Shanghai":
        return 250;
      case "Asia/Singapore":
        return 292;
      case "Asia/Taipei":
        return 255;
      case "Asia/Tashkent":
        return 300;
      case "Asia/Tbilisi":
        return 258;
      case "Asia/Tehran":
        return 264;
      case "Asia/Tel_Aviv":
        return 778;
      case "Asia/Thimbu":
        return 245;
      case "Asia/Tokyo":
        return 267;
      case "Asia/Ujung_Pandang":
        return 262;
      case "Asia/Ulaanbaatar":
        return 281;
      case "Asia/Ulan_Bator":
        return 793;
      case "Asia/Urumqi":
        return 252;
      case "Asia/Vientiane":
        return 276;
      case "Asia/Vladivostok":
        return 309;
      case "Asia/Yakutsk":
        return 308;
      case "Asia/Yekaterinburg":
        return 303;
      case "Asia/Yerevan":
        return 241;
      case "Atlantic/Azores":
        return 336;
      case "Atlantic/Bermuda":
        return 330;
      case "Atlantic/Canary":
        return 338;
      case "Atlantic/Cape_Verde":
        return 339;
      case "Atlantic/Faeroe":
        return 333;
      case "Atlantic/Jan_Mayen":
        return 335;
      case "Atlantic/Madeira":
        return 337;
      case "Atlantic/Reykjavik":
        return 334;
      case "Atlantic/South_Georgia":
        return 332;
      case "Atlantic/St_Helena":
        return 340;
      case "Atlantic/Stanley":
        return 331;
      case "Australia/ACT":
        return 864;
      case "Australia/Adelaide":
        return 349;
      case "Australia/Brisbane":
        return 347;
      case "Australia/Broken_Hill":
        return 353;
      case "Australia/Canberra":
        return 1376;
      case "Australia/Darwin":
        return 345;
      case "Australia/Hobart":
        return 350;
      case "Australia/LHI":
        return 866;
      case "Australia/Lindeman":
        return 348;
      case "Australia/Lord_Howe":
        return 354;
      case "Australia/Melbourne":
        return 351;
      case "Australia/NSW":
        return 1888;
      case "Australia/North":
        return 857;
      case "Australia/Perth":
        return 346;
      case "Australia/Queensland":
        return 859;
      case "Australia/South":
        return 861;
      case "Australia/Sydney":
        return 352;
      case "Australia/Tasmania":
        return 862;
      case "Australia/Victoria":
        return 863;
      case "Australia/West":
        return 858;
      case "Australia/Yancowinna":
        return 865;
      case "Brazil/Acre":
        return 705;
      case "Brazil/DeNoronha":
        return 695;
      case "Brazil/East":
        return 700;
      case "Brazil/West":
        return 704;
      case "CET":
        return 366;
      case "CST":
        return 1637;
      case "CST6CDT":
        return 1125;
      case "Canada/Atlantic":
        return 632;
      case "Canada/Central":
        return 638;
      case "Canada/East-Saskatchewan":
        return 639;
      case "Canada/Eastern":
        return 634;
      case "Canada/Mountain":
        return 641;
      case "Canada/Newfoundland":
        return 630;
      case "Canada/Pacific":
        return 642;
      case "Canada/Saskatchewan":
        return 1151;
      case "Canada/Yukon":
        return 650;
      case "Chile/Continental":
        return 706;
      case "Chile/EasterIsland":
        return 963;
      case "Cuba":
        return 665;
      case "EET":
        return 368;
      case "EST":
        return 1636;
      case "EST5EDT":
        return 1124;
      case "Egypt":
        return 556;
      case "Eire":
        return 883;
      case "Etc/GMT":
        return 1;
      case "Etc/GMT+0":
        return 1025;
      case "Etc/GMT+1":
        return 16;
      case "Etc/GMT+10":
        return 25;
      case "Etc/GMT+11":
        return 26;
      case "Etc/GMT+12":
        return 27;
      case "Etc/GMT+2":
        return 17;
      case "Etc/GMT+3":
        return 18;
      case "Etc/GMT+4":
        return 19;
      case "Etc/GMT+5":
        return 20;
      case "Etc/GMT+6":
        return 21;
      case "Etc/GMT+7":
        return 22;
      case "Etc/GMT+8":
        return 23;
      case "Etc/GMT+9":
        return 24;
      case "Etc/GMT-0":
        return 2049;
      case "Etc/GMT-1":
        return 15;
      case "Etc/GMT-10":
        return 6;
      case "Etc/GMT-11":
        return 5;
      case "Etc/GMT-12":
        return 4;
      case "Etc/GMT-13":
        return 3;
      case "Etc/GMT-14":
        return 2;
      case "Etc/GMT-2":
        return 14;
      case "Etc/GMT-3":
        return 13;
      case "Etc/GMT-4":
        return 12;
      case "Etc/GMT-5":
        return 11;
      case "Etc/GMT-6":
        return 10;
      case "Etc/GMT-7":
        return 9;
      case "Etc/GMT-8":
        return 8;
      case "Etc/GMT-9":
        return 7;
      case "Etc/GMT0":
        return 3073;
      case "Etc/Greenwich":
        return 4097;
      case "Etc/UCT":
        return 29;
      case "Etc/UTC":
        return 28;
      case "Etc/Universal":
        return 1052;
      case "Etc/Zulu":
        return 2076;
      case "Europe/Amsterdam":
        return 396;
      case "Europe/Andorra":
        return 373;
      case "Europe/Athens":
        return 385;
      case "Europe/Belfast":
        return 370;
      case "Europe/Belgrade":
        return 412;
      case "Europe/Berlin":
        return 383;
      case "Europe/Bratislava":
        return 890;
      case "Europe/Brussels":
        return 376;
      case "Europe/Bucharest":
        return 400;
      case "Europe/Budapest":
        return 386;
      case "Europe/Chisinau":
        return 393;
      case "Europe/Copenhagen":
        return 379;
      case "Europe/Dublin":
        return 371;
      case "Europe/Gibraltar":
        return 384;
      case "Europe/Helsinki":
        return 381;
      case "Europe/Istanbul":
        return 407;
      case "Europe/Kaliningrad":
        return 401;
      case "Europe/Kiev":
        return 408;
      case "Europe/Lisbon":
        return 399;
      case "Europe/Ljubljana":
        return 924;
      case "Europe/London":
        return 369;
      case "Europe/Luxembourg":
        return 391;
      case "Europe/Madrid":
        return 404;
      case "Europe/Malta":
        return 392;
      case "Europe/Minsk":
        return 375;
      case "Europe/Monaco":
        return 395;
      case "Europe/Moscow":
        return 402;
      case "Europe/Oslo":
        return 397;
      case "Europe/Paris":
        return 382;
      case "Europe/Prague":
        return 378;
      case "Europe/Riga":
        return 388;
      case "Europe/Rome":
        return 387;
      case "Europe/Samara":
        return 403;
      case "Europe/San_Marino":
        return 1411;
      case "Europe/Sarajevo":
        return 1436;
      case "Europe/Simferopol":
        return 411;
      case "Europe/Skopje":
        return 1948;
      case "Europe/Sofia":
        return 377;
      case "Europe/Stockholm":
        return 405;
      case "Europe/Tallinn":
        return 380;
      case "Europe/Tirane":
        return 372;
      case "Europe/Tiraspol":
        return 394;
      case "Europe/Uzhgorod":
        return 409;
      case "Europe/Vaduz":
        return 389;
      case "Europe/Vatican":
        return 899;
      case "Europe/Vienna":
        return 374;
      case "Europe/Vilnius":
        return 390;
      case "Europe/Warsaw":
        return 398;
      case "Europe/Zagreb":
        return 2460;
      case "Europe/Zaporozhye":
        return 410;
      case "Europe/Zurich":
        return 406;
      case "GB":
        return 881;
      case "GB-Eire":
        return 1393;
      case "GMT":
        return 513;
      case "GMT+0":
        return 1537;
      case "GMT-0":
        return 2561;
      case "GMT0":
        return 3585;
      case "Greenwich":
        return 4609;
      case "HST":
        return 1474;
      case "Hongkong":
        return 766;
      case "Iceland":
        return 846;
      case "Indian/Antananarivo":
        return 438;
      case "Indian/Chagos":
        return 436;
      case "Indian/Christmas":
        return 439;
      case "Indian/Cocos":
        return 440;
      case "Indian/Comoro":
        return 441;
      case "Indian/Kerguelen":
        return 435;
      case "Indian/Mahe":
        return 442;
      case "Indian/Maldives":
        return 437;
      case "Indian/Mauritius":
        return 443;
      case "Indian/Mayotte":
        return 444;
      case "Indian/Reunion":
        return 445;
      case "Iran":
        return 776;
      case "Israel":
        return 1290;
      case "Jamaica":
        return 674;
      case "Japan":
        return 779;
      case "Kwajalein":
        return 976;
      case "Libya":
        return 568;
      case "MET":
        return 367;
      case "MST":
        return 2662;
      case "MST7MDT":
        return 2150;
      case "Mexico/BajaNorte":
        return 1169;
      case "Mexico/BajaSur":
        return 656;
      case "Mexico/General":
        return 653;
      case "Mideast/Riyadh87":
        return 801;
      case "Mideast/Riyadh88":
        return 802;
      case "Mideast/Riyadh89":
        return 803;
      case "NZ":
        return 983;
      case "NZ-CHAT":
        return 984;
      case "Navajo":
        return 614;
      case "PRC":
        return 762;
      case "PST":
        return 2151;
      case "PST8PDT":
        return 1127;
      case "Pacific/Apia":
        return 479;
      case "Pacific/Auckland":
        return 471;
      case "Pacific/Chatham":
        return 472;
      case "Pacific/Easter":
        return 451;
      case "Pacific/Efate":
        return 488;
      case "Pacific/Enderbury":
        return 460;
      case "Pacific/Fakaofo":
        return 482;
      case "Pacific/Fiji":
        return 454;
      case "Pacific/Funafuti":
        return 484;
      case "Pacific/Galapagos":
        return 452;
      case "Pacific/Gambier":
        return 455;
      case "Pacific/Guadalcanal":
        return 481;
      case "Pacific/Guam":
        return 458;
      case "Pacific/Honolulu":
        return 450;
      case "Pacific/Johnston":
        return 485;
      case "Pacific/Kiritimati":
        return 461;
      case "Pacific/Kosrae":
        return 468;
      case "Pacific/Kwajalein":
        return 464;
      case "Pacific/Majuro":
        return 463;
      case "Pacific/Marquesas":
        return 456;
      case "Pacific/Midway":
        return 486;
      case "Pacific/Nauru":
        return 469;
      case "Pacific/Niue":
        return 473;
      case "Pacific/Norfolk":
        return 474;
      case "Pacific/Noumea":
        return 470;
      case "Pacific/Pago_Pago":
        return 478;
      case "Pacific/Palau":
        return 475;
      case "Pacific/Pitcairn":
        return 477;
      case "Pacific/Ponape":
        return 467;
      case "Pacific/Port_Moresby":
        return 476;
      case "Pacific/Rarotonga":
        return 453;
      case "Pacific/Saipan":
        return 462;
      case "Pacific/Samoa":
        return 1502;
      case "Pacific/Tahiti":
        return 457;
      case "Pacific/Tarawa":
        return 459;
      case "Pacific/Tongatapu":
        return 483;
      case "Pacific/Truk":
        return 466;
      case "Pacific/Wake":
        return 487;
      case "Pacific/Wallis":
        return 489;
      case "Pacific/Yap":
        return 465;
      case "Poland":
        return 910;
      case "Portugal":
        return 911;
      case "ROC":
        return 767;
      case "ROK":
        return 785;
      case "Singapore":
        return 804;
      case "Turkey":
        return 919;
      case "UCT":
        return 541;
      case "US/Alaska":
        return 618;
      case "US/Aleutian":
        return 1132;
      case "US/Arizona":
        return 621;
      case "US/Central":
        return 613;
      case "US/East-Indiana":
        return 1135;
      case "US/Eastern":
        return 612;
      case "US/Hawaii":
        return 962;
      case "US/Indiana-Starke":
        return 1137;
      case "US/Michigan":
        return 628;
      case "US/Mountain":
        return 1126;
      case "US/Pacific":
        return 615;
      case "US/Pacific-New":
        return 1639;
      case "US/Samoa":
        return 990;
      case "UTC":
        return 540;
      case "Universal":
        return 1564;
      case "W-SU":
        return 914;
      case "WET":
        return 365;
      case "Zulu":
        return 2588;
      default:
        return INV_ZONEID;
    }
  }

  public static String getRegion(int paramInt) {
    switch (paramInt) {
      case 1:
        return "Etc/GMT";
      case 2:
        return "Etc/GMT-14";
      case 3:
        return "Etc/GMT-13";
      case 4:
        return "Etc/GMT-12";
      case 5:
        return "Etc/GMT-11";
      case 6:
        return "Etc/GMT-10";
      case 7:
        return "Etc/GMT-9";
      case 8:
        return "Etc/GMT-8";
      case 9:
        return "Etc/GMT-7";
      case 10:
        return "Etc/GMT-6";
      case 11:
        return "Etc/GMT-5";
      case 12:
        return "Etc/GMT-4";
      case 13:
        return "Etc/GMT-3";
      case 14:
        return "Etc/GMT-2";
      case 15:
        return "Etc/GMT-1";
      case 16:
        return "Etc/GMT+1";
      case 17:
        return "Etc/GMT+2";
      case 18:
        return "Etc/GMT+3";
      case 19:
        return "Etc/GMT+4";
      case 20:
        return "Etc/GMT+5";
      case 21:
        return "Etc/GMT+6";
      case 22:
        return "Etc/GMT+7";
      case 23:
        return "Etc/GMT+8";
      case 24:
        return "Etc/GMT+9";
      case 25:
        return "Etc/GMT+10";
      case 26:
        return "Etc/GMT+11";
      case 27:
        return "Etc/GMT+12";
      case 28:
        return "Etc/UTC";
      case 29:
        return "Etc/UCT";
      case 31:
        return "Africa/Luanda";
      case 32:
        return "Africa/Porto-Novo";
      case 33:
        return "Africa/Gaborone";
      case 34:
        return "Africa/Ouagadougou";
      case 35:
        return "Africa/Bujumbura";
      case 36:
        return "Africa/Douala";
      case 37:
        return "Africa/Bangui";
      case 38:
        return "Africa/Ndjamena";
      case 39:
        return "Africa/Kinshasa";
      case 40:
        return "Africa/Lubumbashi";
      case 41:
        return "Africa/Brazzaville";
      case 43:
        return "Africa/Djibouti";
      case 44:
        return "Africa/Cairo";
      case 45:
        return "Africa/Malabo";
      case 46:
        return "Africa/Asmera";
      case 48:
        return "Africa/Libreville";
      case 49:
        return "Africa/Banjul";
      case 51:
        return "Africa/Conakry";
      case 52:
        return "Africa/Bissau";
      case 53:
        return "Africa/Nairobi";
      case 54:
        return "Africa/Maseru";
      case 55:
        return "Africa/Monrovia";
      case 56:
        return "Africa/Tripoli";
      case 57:
        return "Africa/Blantyre";
      case 58:
        return "Africa/Bamako";
      case 59:
        return "Africa/Timbuktu";
      case 60:
        return "Africa/Nouakchott";
      case 61:
        return "Africa/Casablanca";
      case 62:
        return "Africa/El_Aaiun";
      case 63:
        return "Africa/Maputo";
      case 64:
        return "Africa/Windhoek";
      case 65:
        return "Africa/Niamey";
      case 66:
        return "Africa/Lagos";
      case 67:
        return "Africa/Kigali";
      case 68:
        return "Africa/Sao_Tome";
      case 69:
        return "Africa/Dakar";
      case 70:
        return "Africa/Freetown";
      case 71:
        return "Africa/Mogadishu";
      case 72:
        return "Africa/Johannesburg";
      case 73:
        return "Africa/Khartoum";
      case 74:
        return "Africa/Mbabane";
      case 75:
        return "Africa/Dar_es_Salaam";
      case 76:
        return "Africa/Lome";
      case 77:
        return "Africa/Tunis";
      case 78:
        return "Africa/Kampala";
      case 79:
        return "Africa/Lusaka";
      case 80:
        return "Africa/Harare";
      case 81:
        return "Africa/Ceuta";
      case 100:
        return "America/New_York";
      case 101:
        return "America/Chicago";
      case 102:
        return "America/Denver";
      case 103:
        return "America/Los_Angeles";
      case 104:
        return "America/Juneau";
      case 105:
        return "America/Yakutat";
      case 106:
        return "America/Anchorage";
      case 107:
        return "America/Nome";
      case 108:
        return "America/Adak";
      case 109:
        return "America/Phoenix";
      case 110:
        return "America/Boise";
      case 111:
        return "America/Indianapolis";
      case 112:
        return "America/Indiana/Marengo";
      case 113:
        return "America/Indiana/Knox";
      case 114:
        return "America/Indiana/Vevay";
      case 115:
        return "America/Louisville";
      case 116:
        return "America/Detroit";
      case 117:
        return "America/Menominee";
      case 118:
        return "America/St_Johns";
      case 119:
        return "America/Goose_Bay";
      case 120:
        return "America/Halifax";
      case 121:
        return "America/Glace_Bay";
      case 122:
        return "America/Montreal";
      case 123:
        return "America/Thunder_Bay";
      case 124:
        return "America/Nipigon";
      case 125:
        return "America/Rainy_River";
      case 126:
        return "America/Winnipeg";
      case 127:
        return "America/Regina";
      case 128:
        return "America/Swift_Current";
      case 129:
        return "America/Edmonton";
      case 130:
        return "America/Vancouver";
      case 131:
        return "America/Dawson_Creek";
      case 132:
        return "America/Pangnirtung";
      case 133:
        return "America/Iqaluit";
      case 134:
        return "America/Rankin_Inlet";
      case 135:
        return "America/Cambridge_Bay";
      case 136:
        return "America/Yellowknife";
      case 137:
        return "America/Inuvik";
      case 138:
        return "America/Whitehorse";
      case 139:
        return "America/Dawson";
      case 140:
        return "America/Cancun";
      case 141:
        return "America/Mexico_City";
      case 142:
        return "America/Chihuahua";
      case 143:
        return "America/Hermosillo";
      case 144:
        return "America/Mazatlan";
      case 145:
        return "America/Tijuana";
      case 146:
        return "America/Anguilla";
      case 147:
        return "America/Antigua";
      case 148:
        return "America/Nassau";
      case 149:
        return "America/Barbados";
      case 150:
        return "America/Belize";
      case 151:
        return "America/Cayman";
      case 152:
        return "America/Costa_Rica";
      case 153:
        return "America/Havana";
      case 154:
        return "America/Dominica";
      case 155:
        return "America/Santo_Domingo";
      case 156:
        return "America/El_Salvador";
      case 157:
        return "America/Grenada";
      case 158:
        return "America/Guadeloupe";
      case 159:
        return "America/Guatemala";
      case 160:
        return "America/Port-au-Prince";
      case 161:
        return "America/Tegucigalpa";
      case 162:
        return "America/Jamaica";
      case 163:
        return "America/Martinique";
      case 164:
        return "America/Montserrat";
      case 165:
        return "America/Managua";
      case 166:
        return "America/Panama";
      case 167:
        return "America/Puerto_Rico";
      case 168:
        return "America/St_Kitts";
      case 169:
        return "America/St_Lucia";
      case 170:
        return "America/Miquelon";
      case 171:
        return "America/St_Vincent";
      case 172:
        return "America/Grand_Turk";
      case 173:
        return "America/Tortola";
      case 174:
        return "America/St_Thomas";
      case 175:
        return "America/Buenos_Aires";
      case 176:
        return "America/Rosario";
      case 177:
        return "America/Cordoba";
      case 178:
        return "America/Jujuy";
      case 179:
        return "America/Catamarca";
      case 180:
        return "America/Mendoza";
      case 181:
        return "America/Aruba";
      case 182:
        return "America/La_Paz";
      case 183:
        return "America/Noronha";
      case 184:
        return "America/Belem";
      case 185:
        return "America/Fortaleza";
      case 186:
        return "America/Araguaina";
      case 187:
        return "America/Maceio";
      case 188:
        return "America/Sao_Paulo";
      case 189:
        return "America/Cuiaba";
      case 190:
        return "America/Porto_Velho";
      case 191:
        return "America/Boa_Vista";
      case 192:
        return "America/Manaus";
      case 193:
        return "America/Porto_Acre";
      case 194:
        return "America/Santiago";
      case 195:
        return "America/Bogota";
      case 196:
        return "America/Curacao";
      case 197:
        return "America/Guayaquil";
      case 198:
        return "America/Cayenne";
      case 199:
        return "America/Guyana";
      case 200:
        return "America/Asuncion";
      case 201:
        return "America/Lima";
      case 202:
        return "America/Paramaribo";
      case 203:
        return "America/Port_of_Spain";
      case 204:
        return "America/Montevideo";
      case 205:
        return "America/Caracas";
      case 206:
        return "America/Scoresbysund";
      case 207:
        return "America/Godthab";
      case 208:
        return "America/Thule";
      case 230:
        return "Antarctica/Casey";
      case 231:
        return "Antarctica/Davis";
      case 232:
        return "Antarctica/Mawson";
      case 233:
        return "Antarctica/DumontDUrville";
      case 234:
        return "Antarctica/Syowa";
      case 235:
        return "Antarctica/Palmer";
      case 236:
        return "Antarctica/McMurdo";
      case 240:
        return "Asia/Kabul";
      case 241:
        return "Asia/Yerevan";
      case 242:
        return "Asia/Baku";
      case 243:
        return "Asia/Bahrain";
      case 244:
        return "Asia/Dacca";
      case 245:
        return "Asia/Thimbu";
      case 246:
        return "Asia/Brunei";
      case 247:
        return "Asia/Rangoon";
      case 248:
        return "Asia/Phnom_Penh";
      case 249:
        return "Asia/Harbin";
      case 250:
        return "Asia/Shanghai";
      case 251:
        return "Asia/Chungking";
      case 252:
        return "Asia/Urumqi";
      case 253:
        return "Asia/Kashgar";
      case 254:
        return "Asia/Hong_Kong";
      case 255:
        return "Asia/Taipei";
      case 256:
        return "Asia/Macao";
      case 257:
        return "Asia/Nicosia";
      case 258:
        return "Asia/Tbilisi";
      case 259:
        return "Asia/Dili";
      case 260:
        return "Asia/Calcutta";
      case 261:
        return "Asia/Jakarta";
      case 262:
        return "Asia/Ujung_Pandang";
      case 263:
        return "Asia/Jayapura";
      case 264:
        return "Asia/Tehran";
      case 265:
        return "Asia/Baghdad";
      case 266:
        return "Asia/Jerusalem";
      case 267:
        return "Asia/Tokyo";
      case 268:
        return "Asia/Amman";
      case 269:
        return "Asia/Almaty";
      case 270:
        return "Asia/Aqtobe";
      case 271:
        return "Asia/Aqtau";
      case 272:
        return "Asia/Bishkek";
      case 273:
        return "Asia/Seoul";
      case 274:
        return "Asia/Pyongyang";
      case 275:
        return "Asia/Kuwait";
      case 276:
        return "Asia/Vientiane";
      case 277:
        return "Asia/Beirut";
      case 278:
        return "Asia/Kuala_Lumpur";
      case 279:
        return "Asia/Kuching";
      case 280:
        return "Asia/Hovd";
      case 281:
        return "Asia/Ulaanbaatar";
      case 282:
        return "Asia/Katmandu";
      case 283:
        return "Asia/Muscat";
      case 284:
        return "Asia/Karachi";
      case 285:
        return "Asia/Gaza";
      case 286:
        return "Asia/Manila";
      case 287:
        return "Asia/Qatar";
      case 288:
        return "Asia/Riyadh";
      case 289:
        return "Asia/Riyadh87";
      case 290:
        return "Asia/Riyadh88";
      case 291:
        return "Asia/Riyadh89";
      case 292:
        return "Asia/Singapore";
      case 293:
        return "Asia/Colombo";
      case 294:
        return "Asia/Damascus";
      case 295:
        return "Asia/Dushanbe";
      case 296:
        return "Asia/Bangkok";
      case 297:
        return "Asia/Ashkhabad";
      case 298:
        return "Asia/Dubai";
      case 299:
        return "Asia/Samarkand";
      case 300:
        return "Asia/Tashkent";
      case 301:
        return "Asia/Saigon";
      case 302:
        return "Asia/Aden";
      case 303:
        return "Asia/Yekaterinburg";
      case 304:
        return "Asia/Omsk";
      case 305:
        return "Asia/Novosibirsk";
      case 306:
        return "Asia/Krasnoyarsk";
      case 307:
        return "Asia/Irkutsk";
      case 308:
        return "Asia/Yakutsk";
      case 309:
        return "Asia/Vladivostok";
      case 310:
        return "Asia/Magadan";
      case 311:
        return "Asia/Kamchatka";
      case 312:
        return "Asia/Anadyr";
      case 330:
        return "Atlantic/Bermuda";
      case 331:
        return "Atlantic/Stanley";
      case 332:
        return "Atlantic/South_Georgia";
      case 333:
        return "Atlantic/Faeroe";
      case 334:
        return "Atlantic/Reykjavik";
      case 335:
        return "Atlantic/Jan_Mayen";
      case 336:
        return "Atlantic/Azores";
      case 337:
        return "Atlantic/Madeira";
      case 338:
        return "Atlantic/Canary";
      case 339:
        return "Atlantic/Cape_Verde";
      case 340:
        return "Atlantic/St_Helena";
      case 345:
        return "Australia/Darwin";
      case 346:
        return "Australia/Perth";
      case 347:
        return "Australia/Brisbane";
      case 348:
        return "Australia/Lindeman";
      case 349:
        return "Australia/Adelaide";
      case 350:
        return "Australia/Hobart";
      case 351:
        return "Australia/Melbourne";
      case 352:
        return "Australia/Sydney";
      case 353:
        return "Australia/Broken_Hill";
      case 354:
        return "Australia/Lord_Howe";
      case 365:
        return "WET";
      case 366:
        return "CET";
      case 367:
        return "MET";
      case 368:
        return "EET";
      case 369:
        return "Europe/London";
      case 370:
        return "Europe/Belfast";
      case 371:
        return "Europe/Dublin";
      case 372:
        return "Europe/Tirane";
      case 373:
        return "Europe/Andorra";
      case 374:
        return "Europe/Vienna";
      case 375:
        return "Europe/Minsk";
      case 376:
        return "Europe/Brussels";
      case 377:
        return "Europe/Sofia";
      case 378:
        return "Europe/Prague";
      case 379:
        return "Europe/Copenhagen";
      case 380:
        return "Europe/Tallinn";
      case 381:
        return "Europe/Helsinki";
      case 382:
        return "Europe/Paris";
      case 383:
        return "Europe/Berlin";
      case 384:
        return "Europe/Gibraltar";
      case 385:
        return "Europe/Athens";
      case 386:
        return "Europe/Budapest";
      case 387:
        return "Europe/Rome";
      case 388:
        return "Europe/Riga";
      case 389:
        return "Europe/Vaduz";
      case 390:
        return "Europe/Vilnius";
      case 391:
        return "Europe/Luxembourg";
      case 392:
        return "Europe/Malta";
      case 393:
        return "Europe/Chisinau";
      case 394:
        return "Europe/Tiraspol";
      case 395:
        return "Europe/Monaco";
      case 396:
        return "Europe/Amsterdam";
      case 397:
        return "Europe/Oslo";
      case 398:
        return "Europe/Warsaw";
      case 399:
        return "Europe/Lisbon";
      case 400:
        return "Europe/Bucharest";
      case 401:
        return "Europe/Kaliningrad";
      case 402:
        return "Europe/Moscow";
      case 403:
        return "Europe/Samara";
      case 404:
        return "Europe/Madrid";
      case 405:
        return "Europe/Stockholm";
      case 406:
        return "Europe/Zurich";
      case 407:
        return "Europe/Istanbul";
      case 408:
        return "Europe/Kiev";
      case 409:
        return "Europe/Uzhgorod";
      case 410:
        return "Europe/Zaporozhye";
      case 411:
        return "Europe/Simferopol";
      case 412:
        return "Europe/Belgrade";
      case 435:
        return "Indian/Kerguelen";
      case 436:
        return "Indian/Chagos";
      case 437:
        return "Indian/Maldives";
      case 438:
        return "Indian/Antananarivo";
      case 439:
        return "Indian/Christmas";
      case 440:
        return "Indian/Cocos";
      case 441:
        return "Indian/Comoro";
      case 442:
        return "Indian/Mahe";
      case 443:
        return "Indian/Mauritius";
      case 444:
        return "Indian/Mayotte";
      case 445:
        return "Indian/Reunion";
      case 450:
        return "Pacific/Honolulu";
      case 451:
        return "Pacific/Easter";
      case 452:
        return "Pacific/Galapagos";
      case 453:
        return "Pacific/Rarotonga";
      case 454:
        return "Pacific/Fiji";
      case 455:
        return "Pacific/Gambier";
      case 456:
        return "Pacific/Marquesas";
      case 457:
        return "Pacific/Tahiti";
      case 458:
        return "Pacific/Guam";
      case 459:
        return "Pacific/Tarawa";
      case 460:
        return "Pacific/Enderbury";
      case 461:
        return "Pacific/Kiritimati";
      case 462:
        return "Pacific/Saipan";
      case 463:
        return "Pacific/Majuro";
      case 464:
        return "Pacific/Kwajalein";
      case 465:
        return "Pacific/Yap";
      case 466:
        return "Pacific/Truk";
      case 467:
        return "Pacific/Ponape";
      case 468:
        return "Pacific/Kosrae";
      case 469:
        return "Pacific/Nauru";
      case 470:
        return "Pacific/Noumea";
      case 471:
        return "Pacific/Auckland";
      case 472:
        return "Pacific/Chatham";
      case 473:
        return "Pacific/Niue";
      case 474:
        return "Pacific/Norfolk";
      case 475:
        return "Pacific/Palau";
      case 476:
        return "Pacific/Port_Moresby";
      case 477:
        return "Pacific/Pitcairn";
      case 478:
        return "Pacific/Pago_Pago";
      case 479:
        return "Pacific/Apia";
      case 481:
        return "Pacific/Guadalcanal";
      case 482:
        return "Pacific/Fakaofo";
      case 483:
        return "Pacific/Tongatapu";
      case 484:
        return "Pacific/Funafuti";
      case 485:
        return "Pacific/Johnston";
      case 486:
        return "Pacific/Midway";
      case 487:
        return "Pacific/Wake";
      case 488:
        return "Pacific/Efate";
      case 489:
        return "Pacific/Wallis";
      case 513:
        return "GMT";
      case 540:
        return "UTC";
      case 541:
        return "UCT";
      case 556:
        return "Egypt";
      case 568:
        return "Libya";
      case 612:
        return "US/Eastern";
      case 613:
        return "US/Central";
      case 614:
        return "Navajo";
      case 615:
        return "US/Pacific";
      case 618:
        return "US/Alaska";
      case 620:
        return "America/Atka";
      case 621:
        return "US/Arizona";
      case 623:
        return "America/Fort_Wayne";
      case 625:
        return "America/Knox_IN";
      case 628:
        return "US/Michigan";
      case 630:
        return "Canada/Newfoundland";
      case 632:
        return "Canada/Atlantic";
      case 634:
        return "Canada/Eastern";
      case 638:
        return "Canada/Central";
      case 639:
        return "Canada/East-Saskatchewan";
      case 641:
        return "Canada/Mountain";
      case 642:
        return "Canada/Pacific";
      case 650:
        return "Canada/Yukon";
      case 653:
        return "Mexico/General";
      case 656:
        return "Mexico/BajaSur";
      case 657:
        return "America/Ensenada";
      case 665:
        return "Cuba";
      case 674:
        return "Jamaica";
      case 686:
        return "America/Virgin";
      case 695:
        return "Brazil/DeNoronha";
      case 700:
        return "Brazil/East";
      case 704:
        return "Brazil/West";
      case 705:
        return "Brazil/Acre";
      case 706:
        return "Chile/Continental";
      case 748:
        return "Antarctica/South_Pole";
      case 762:
        return "PRC";
      case 766:
        return "Hongkong";
      case 767:
        return "ROC";
      case 776:
        return "Iran";
      case 778:
        return "Asia/Tel_Aviv";
      case 779:
        return "Japan";
      case 785:
        return "ROK";
      case 793:
        return "Asia/Ulan_Bator";
      case 801:
        return "Mideast/Riyadh87";
      case 802:
        return "Mideast/Riyadh88";
      case 803:
        return "Mideast/Riyadh89";
      case 804:
        return "Singapore";
      case 846:
        return "Iceland";
      case 857:
        return "Australia/North";
      case 858:
        return "Australia/West";
      case 859:
        return "Australia/Queensland";
      case 861:
        return "Australia/South";
      case 862:
        return "Australia/Tasmania";
      case 863:
        return "Australia/Victoria";
      case 864:
        return "Australia/ACT";
      case 865:
        return "Australia/Yancowinna";
      case 866:
        return "Australia/LHI";
      case 881:
        return "GB";
      case 883:
        return "Eire";
      case 890:
        return "Europe/Bratislava";
      case 899:
        return "Europe/Vatican";
      case 910:
        return "Poland";
      case 911:
        return "Portugal";
      case 914:
        return "W-SU";
      case 919:
        return "Turkey";
      case 924:
        return "Europe/Ljubljana";
      case 962:
        return "US/Hawaii";
      case 963:
        return "Chile/EasterIsland";
      case 976:
        return "Kwajalein";
      case 983:
        return "NZ";
      case 984:
        return "NZ-CHAT";
      case 990:
        return "US/Samoa";
      case 1025:
        return "Etc/GMT+0";
      case 1052:
        return "Etc/Universal";
      case 1124:
        return "EST5EDT";
      case 1125:
        return "CST6CDT";
      case 1126:
        return "US/Mountain";
      case 1127:
        return "PST8PDT";
      case 1132:
        return "US/Aleutian";
      case 1135:
        return "US/East-Indiana";
      case 1137:
        return "US/Indiana-Starke";
      case 1151:
        return "Canada/Saskatchewan";
      case 1169:
        return "Mexico/BajaNorte";
      case 1290:
        return "Israel";
      case 1376:
        return "Australia/Canberra";
      case 1393:
        return "GB-Eire";
      case 1411:
        return "Europe/San_Marino";
      case 1431:
        return "Asia/Istanbul";
      case 1436:
        return "Europe/Sarajevo";
      case 1474:
        return "HST";
      case 1502:
        return "Pacific/Samoa";
      case 1537:
        return "GMT+0";
      case 1564:
        return "Universal";
      case 1636:
        return "EST";
      case 1637:
        return "CST";
      case 1638:
        return "America/Shiprock";
      case 1639:
        return "US/Pacific-New";
      case 1647:
        return "America/Indiana/Indianapolis";
      case 1888:
        return "Australia/NSW";
      case 1948:
        return "Europe/Skopje";
      case 2049:
        return "Etc/GMT-0";
      case 2076:
        return "Etc/Zulu";
      case 2150:
        return "MST7MDT";
      case 2151:
        return "PST";
      case 2460:
        return "Europe/Zagreb";
      case 2561:
        return "GMT-0";
      case 2588:
        return "Zulu";
      case 2662:
        return "MST";
      case 3073:
        return "Etc/GMT0";
      case 3585:
        return "GMT0";
      case 4097:
        return "Etc/Greenwich";
      case 4609:
        return "Greenwich";
      default:
        return null;
    }
  }

}
