CREATE TABLE JAVA_TIME (
  ID NUMBER NOT NULL,
  OFFSET_COLUMN TIMESTAMP(6) WITH TIME ZONE,
  ZONE_COLUMN TIMESTAMP(6) WITH TIME ZONE,
  CALENDAR_COLUMN TIMESTAMP(6) WITH TIME ZONE,
  YEAR_TO_MONTH_COLUMN INTERVAL YEAR(9) TO MONTH,
  DAY_TO_SECOND_COLUMN INTERVAL DAY(9) TO SECOND(9),
  PRIMARY KEY (ID)
);