CREATE TABLE JAVA_TIME_WITH_ZONE (
  ID NUMBER NOT NULL,
  ZONED_TIME TIMESTAMP WITH TIME ZONE,
  OFFSET_TIME TIMESTAMP WITH TIME ZONE,
  YEAR_TO_MONTH_COLUMN INTERVAL YEAR(9) TO MONTH,
  DAY_TO_SECOND_COLUMN INTERVAL DAY(9) TO SECOND(9),
  PRIMARY KEY (ID)
);
