CREATE TABLE JAVA_TIME (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  DATE_COLUMN DATE,
  TIME_COLUMN TIME,
  TIMESTAMP_COLUMN TIMESTAMP
--  TIME_WITH_TIMEZONE_COLUMN TIME WITH TIMEZONE NOT NULL,
--  TIMESTAMP_WITH_TIMEZONE_COLUMN TIMESTAMP WITH TIMEZONE NOT NULL
);