CREATE TABLE JAVA_TIME_WITH_ZONE (
  ID BIGINT NOT NULL,
  ZONED_TIME TIMESTAMP WITH TIME ZONE,
  OFFSET_TIME TIMESTAMP WITH TIME ZONE,
  DATE_COLUMN DATE,
  TIME_COLUMN TIME,
  TIMESTAMP_COLUMN TIMESTAMP,
  PRIMARY KEY (ID)
);