CREATE TABLE JAVA_TIME (
  ID INT NOT NULL,
  DATE_COLUMN DATE,
  TIME_COLUMN TIME,
  TIMESTAMP_COLUMN TIMESTAMP,
--  TIME_WITH_TIMEZONE_COLUMN TIME WITH TIMEZONE,
--  TIMESTAMP_WITH_TIMEZONE_COLUMN TIMESTAMP WITH
  PRIMARY KEY (ID)
);