DROP TABLE IF EXISTS JAVA_TIME;
CREATE TABLE JAVA_TIME (
  ID BIGINT NOT NULL,
  DATE_COLUMN DATE NULL,
  TIME_COLUMN TIME NULL,
  TIMESTAMP_COLUMN TIMESTAMP NULL,
  TIMESTAMP_COLUMN_2 TIMESTAMP NULL,
  PRIMARY KEY (ID)
);