CREATE TABLE JAVA_TIME (
  ID NUMBER NOT NULL,
  DATE_COLUMN DATE,
---  TIME_COLUMN TIME,
  TIMESTAMP_COLUMN TIMESTAMP,
  PRIMARY KEY (ID)
--  TIME_WITH_TIMEZONE_COLUMN TIME WITH TIMEZONE,
--  TIMESTAMP_WITH_TIMEZONE_COLUMN TIMESTAMP WITH TIMEZONE
);