DROP TABLE IF EXISTS JAVA_TIME;
CREATE TABLE JAVA_TIME (
  ID BIGINT NOT NULL,
  DATE_COLUMN DATE,
  TIME_COLUMN TIME,
  TIMESTAMP_COLUMN DATETIME2,
  TIMESTAMP_COLUMN_2 DATETIME2,
  PRIMARY KEY (ID)
);